# Generated by Django 6.0.3 on 2026-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorSinCfdi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreComercial', models.CharField(blank=True, max_length=255, null=True)),
                ('RazonSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('RFC', models.CharField(blank=True, max_length=255, null=True)),
                ('Estatus', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoProveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('Contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('Planta', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo2', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo3', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPersona', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoPostal', models.CharField(blank=True, max_length=255, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('noInt', models.CharField(blank=True, max_length=255, null=True)),
                ('noExt', models.CharField(blank=True, max_length=255, null=True)),
                ('colonia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('constancia', models.IntegerField(default=0)),
                ('fecha_constancia1', models.DateField(blank=True, null=True)),
                ('constancia2', models.IntegerField(default=0)),
                ('constancia2_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_constancia2', models.DateField(blank=True, null=True)),
                ('constancia3', models.IntegerField(default=0)),
                ('constancia3_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_constancia3', models.DateField(blank=True, null=True)),
                ('constancia4', models.CharField(blank=True, max_length=100, null=True)),
                ('constancia4_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_constancia4', models.DateField(blank=True, null=True)),
                ('rfc_identy', models.CharField(blank=True, max_length=255, null=True)),
                ('msjefos', models.IntegerField(default=0)),
                ('url', models.TextField(blank=True, null=True)),
                ('url2', models.CharField(blank=True, max_length=255, null=True)),
                ('consultado', models.IntegerField(default=0)),
                ('ano_actual', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor sin CFDI',
                'verbose_name_plural': 'Proveedores sin CFDI',
                'db_table': 'proveedores_sin_cfdi',
                'managed': True,
            },
        ),
    ]
