# Generated by Django 6.0.3 on 2026-03-21 23:00

import django.db.models.deletion
import fiel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaFiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_cliente', models.CharField(help_text='RFC del cliente (único por empresa)', max_length=13, unique=True)),
                ('archivo_cer', models.FileField(help_text='Archivo .cer', upload_to=fiel.models.fiel_upload_path)),
                ('archivo_key', models.FileField(help_text='Archivo .key', upload_to=fiel.models.fiel_upload_path)),
                ('password', models.CharField(help_text='Contraseña cifrada', max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de validar'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('usuario_login', models.CharField(blank=True, help_text='Login del usuario que cargó', max_length=150)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la carga (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_fiel', to='usuarios_tenant.usuario')),
            ],
            options={
                'verbose_name': 'Carga FIEL',
                'verbose_name_plural': 'Cargas FIEL',
                'db_table': 'cargas_fiel',
            },
        ),
    ]
