# Generated by Django 6.0.3 on 2026-03-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_cliente', models.CharField(max_length=13)),
                ('tipo', models.CharField(choices=[('opinion', 'Opinión de Cumplimiento'), ('constancia', 'Constancia')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
                'db_table': 'configuracion_correo',
            },
        ),
    ]
