# Generated by Django 6.0.3 on 2026-03-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('use_id', models.AutoField(primary_key=True, serialize=False)),
                ('use_login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='use_password', max_length=128)),
                ('use_email', models.EmailField(blank=True, max_length=254)),
                ('use_nombre', models.CharField(max_length=255)),
                ('use_rfc', models.CharField(blank=True, max_length=13)),
                ('use_tipo', models.CharField(choices=[('Admin', 'Admin'), ('Cliente', 'Cliente')], default='Cliente', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
